#!/usr/bin/python

from fortworth import *

spec_file = ARGS[1]
repo = ARGS[2]
branch = ARGS[3]
build_id = ENV.get("BUILD_NUMBER")
build_url = ENV.get("BUILD_URL")

build_info = BuildInfo(repo, branch, build_id, build_url)

rpm_build(spec_file, "source", "build", build_info)
