#!/usr/bin/python

from fortworth import *

command = " ".join(ARGS[1:])

docker_command = ENV.get("DOCKER_COMMAND", "sudo docker")

base_image = get_unique_id()
test_image = get_unique_id()

call("{0} build -t {1} .", docker_command, base_image)

test_conf = """
FROM {base_image}
COPY . /root/project
WORKDIR /root/project
""".format(**locals())

with temp_file(dir=".") as f:
    write(f, test_conf)
    call("{0} build -t {1} -f {2} .", docker_command, test_image, f)

options = [
    "--rm",
    "-v", "/etc/pki/ca-trust:/etc/pki/ca-trust:ro",
    "--security-opt", "label=disable",
]

call("{0} run -it {1} {2} {3}", docker_command, " ".join(options), test_image, command)
call("{0} image rm {1} {2}", docker_command, base_image, test_image)
