#!/usr/bin/python

from fortworth import *

command = " ".join(ARGS[1:])
base_image = get_unique_id()
test_image = get_unique_id()

call("podman build -t {0} .", base_image)

test_conf = """
FROM {base_image}
COPY . /root/project
WORKDIR /root/project
""".format(**locals())

with temp_file(dir=".") as f:
    write(f, test_conf)
    call("podman build -t {0} -f {1} .", test_image, f)

options = [
    "--rm",
    "-v", "/etc/pki/ca-trust:/etc/pki/ca-trust:ro",
    "--security-opt", "label=disable",
]

call("podman run -it {0} {1} {2}", " ".join(options), test_image, command)
call("podman image rm {0} {1}", base_image, test_image)
