#!/usr/bin/python

from fortworth import *

repo = ARGS[1]
branch = ARGS[2]
build_id = ENV.get("BUILD_NUMBER")
build_url = ENV.get("BUILD_URL")

build_data = BuildData(repo, branch, build_id, build_url)

maven_build("source", "build", build_data)
