#!/usr/bin/python

from fortworth import *

repo = ARGS[1]
branch = ARGS[2]
tag = ARGS[3]
build_id = ENV.get("BUILD_NUMBER")
build_url = ENV.get("BUILD_URL")

build_info = BuildInfo(repo, branch, build_id, build_url)

maven_publish("source", "build", build_info, tag)
